export const mockPayload = {
  "id": 680,
  "parent_id": 679,
  "status": "active",
  "order_key": "wc_order_RFGikCByBSeUv",
  "number": "680",
  "currency": "MYR",
  "version": "4.2.2",
  "prices_include_tax": false,
  "date_created": "2020-07-05T17:33:06",
  "date_modified": "2020-07-05T17:33:07",
  "customer_id": 64,
  "discount_total": "0.00",
  "discount_tax": "0.00",
  "shipping_total": "0.00",
  "shipping_tax": "0.00",
  "cart_tax": "0.00",
  "total": "0.00",
  "total_tax": "0.00",
  "billing": {
    "first_name": "Nisa",
    "last_name": "Damia",
    "company": "Nisa Sdn. Bhd.",
    "address_1": "No 3, Jalan 3, Taman 3",
    "address_2": "",
    "city": "Semenyih",
    "state": "SGR",
    "postcode": "63000",
    "country": "MY",
    "email": "fakhri@zen.com.my",
    "phone": ""
  },
  "shipping": {
    "first_name": "",
    "last_name": "",
    "company": "",
    "address_1": "",
    "address_2": "",
    "city": "",
    "state": "",
    "postcode": "",
    "country": ""
  },
  "payment_method": "",
  "payment_method_title": "",
  "transaction_id": "",
  "customer_ip_address": "10.255.0.2",
  "customer_user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0",
  "created_via": "checkout",
  "customer_note": "",
  "date_completed": null,
  "date_paid": "2020-07-06T01:33:06",
  "cart_hash": "",
  "line_items": [
    {
      "id": 128,
      "name": "FOC Subscription",
      "sku": "",
      "product_id": 557,
      "variation_id": 0,
      "quantity": 5,
      "tax_class": "",
      "price": "0.00",
      "subtotal": "0.00",
      "subtotal_tax": "0.00",
      "total": "0.00",
      "total_tax": "0.00",
      "taxes": [],
      "meta": []
    }
  ],
  "tax_lines": [],
  "shipping_lines": [],
  "fee_lines": [],
  "coupon_lines": [],
  "refunds": [],
  "billing_period": "month",
  "billing_interval": "1",
  "resubscribed_from": "",
  "resubscribed_subscription": "",
  "start_date": "2020-07-05T17:33:05",
  "trial_end_date": "",
  "next_payment_date": "",
  "end_date": "2020-08-05T17:33:05",
  "date_completed_gmt": null,
  "date_paid_gmt": "2020-07-05T17:33:06",
  "removed_line_items": []
}